// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQcvcMI7b2gDg4xulw-nYFMYK8dlHmm8',
    appId: '1:887366421028:web:9e3b6fb41a635b6984e6b1',
    messagingSenderId: '887366421028',
    projectId: 'notes-bae95',
    authDomain: 'notes-bae95.firebaseapp.com',
    storageBucket: 'notes-bae95.firebasestorage.app',
    measurementId: 'G-6WSGH00KWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYoEk909Y9g-x6RzrH0OaXP4yV4ZFcrfU',
    appId: '1:887366421028:android:3e0a231237c1fffe84e6b1',
    messagingSenderId: '887366421028',
    projectId: 'notes-bae95',
    storageBucket: 'notes-bae95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdUJZV5GPLd39aRyM8Qt1a8pc97sJdBLI',
    appId: '1:887366421028:ios:1b9163d80976008584e6b1',
    messagingSenderId: '887366421028',
    projectId: 'notes-bae95',
    storageBucket: 'notes-bae95.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdUJZV5GPLd39aRyM8Qt1a8pc97sJdBLI',
    appId: '1:887366421028:ios:1b9163d80976008584e6b1',
    messagingSenderId: '887366421028',
    projectId: 'notes-bae95',
    storageBucket: 'notes-bae95.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrQcvcMI7b2gDg4xulw-nYFMYK8dlHmm8',
    appId: '1:887366421028:web:aa976ee7df4e2d9f84e6b1',
    messagingSenderId: '887366421028',
    projectId: 'notes-bae95',
    authDomain: 'notes-bae95.firebaseapp.com',
    storageBucket: 'notes-bae95.firebasestorage.app',
    measurementId: 'G-2H91S8MPWT',
  );
}
