// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzqGz6WN_EwUmf85tS3zNEpDM5muQ99LQ',
    appId: '1:766800886456:web:8725fdf6a67c3901f7d24d',
    messagingSenderId: '766800886456',
    projectId: 'daftarbelanja-b8f58',
    authDomain: 'daftarbelanja-b8f58.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-b8f58-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b8f58.firebasestorage.app',
    measurementId: 'G-QNMJ532YWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWn4jxW_oMRqQbohp-Lb1BEJuoYjguYwo',
    appId: '1:766800886456:android:e0f9af5e6a69dcacf7d24d',
    messagingSenderId: '766800886456',
    projectId: 'daftarbelanja-b8f58',
    databaseURL: 'https://daftarbelanja-b8f58-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b8f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBx9ABw54h7qua5897kZtvnPBOY6nNwlM',
    appId: '1:766800886456:ios:25378168fb59e84ff7d24d',
    messagingSenderId: '766800886456',
    projectId: 'daftarbelanja-b8f58',
    databaseURL: 'https://daftarbelanja-b8f58-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b8f58.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBx9ABw54h7qua5897kZtvnPBOY6nNwlM',
    appId: '1:766800886456:ios:25378168fb59e84ff7d24d',
    messagingSenderId: '766800886456',
    projectId: 'daftarbelanja-b8f58',
    databaseURL: 'https://daftarbelanja-b8f58-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b8f58.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzqGz6WN_EwUmf85tS3zNEpDM5muQ99LQ',
    appId: '1:766800886456:web:238b5860d40833b9f7d24d',
    messagingSenderId: '766800886456',
    projectId: 'daftarbelanja-b8f58',
    authDomain: 'daftarbelanja-b8f58.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-b8f58-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b8f58.firebasestorage.app',
    measurementId: 'G-X5ZJR3QT0M',
  );
}
