// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuXQoGcSgbEbyd0u0fkdYL0irlE4o-hCM',
    appId: '1:310680500311:web:bd8836a807a0ad12ae0b12',
    messagingSenderId: '310680500311',
    projectId: 'cloud-message-bc56e',
    authDomain: 'cloud-message-bc56e.firebaseapp.com',
    storageBucket: 'cloud-message-bc56e.firebasestorage.app',
    measurementId: 'G-CW03W4E432',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMP_urvt6q-y47Hyr0mYI4bWlpT1tVFm8',
    appId: '1:310680500311:android:58d518c8fa1bd511ae0b12',
    messagingSenderId: '310680500311',
    projectId: 'cloud-message-bc56e',
    storageBucket: 'cloud-message-bc56e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKmJCVDYtdBltzKVmi4qZOO4FVR06N94',
    appId: '1:310680500311:ios:605c8f055739538eae0b12',
    messagingSenderId: '310680500311',
    projectId: 'cloud-message-bc56e',
    storageBucket: 'cloud-message-bc56e.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKmJCVDYtdBltzKVmi4qZOO4FVR06N94',
    appId: '1:310680500311:ios:605c8f055739538eae0b12',
    messagingSenderId: '310680500311',
    projectId: 'cloud-message-bc56e',
    storageBucket: 'cloud-message-bc56e.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuXQoGcSgbEbyd0u0fkdYL0irlE4o-hCM',
    appId: '1:310680500311:web:ef7390a4eb9a66b4ae0b12',
    messagingSenderId: '310680500311',
    projectId: 'cloud-message-bc56e',
    authDomain: 'cloud-message-bc56e.firebaseapp.com',
    storageBucket: 'cloud-message-bc56e.firebasestorage.app',
    measurementId: 'G-20VLB1H92J',
  );

}