// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi0e6NUnuN6Bi55KNCMMj8WpbPWC_LNSY',
    appId: '1:570068908413:web:98711337d8cae8bff0f414',
    messagingSenderId: '570068908413',
    projectId: 'mdpgold-eca4c',
    authDomain: 'mdpgold-eca4c.firebaseapp.com',
    databaseURL: 'https://mdpgold-eca4c-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-eca4c.firebasestorage.app',
    measurementId: 'G-6D4Z6F99MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPxBeEX9m2TAhXi4d28HztI4hMoEqh6eo',
    appId: '1:570068908413:android:52ffd6013cc44fabf0f414',
    messagingSenderId: '570068908413',
    projectId: 'mdpgold-eca4c',
    databaseURL: 'https://mdpgold-eca4c-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-eca4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSGv-Fn7oJbD7P6o4IXHBaQT5p3Rd3Fog',
    appId: '1:570068908413:ios:e1584505349b8e8cf0f414',
    messagingSenderId: '570068908413',
    projectId: 'mdpgold-eca4c',
    databaseURL: 'https://mdpgold-eca4c-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-eca4c.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSGv-Fn7oJbD7P6o4IXHBaQT5p3Rd3Fog',
    appId: '1:570068908413:ios:e1584505349b8e8cf0f414',
    messagingSenderId: '570068908413',
    projectId: 'mdpgold-eca4c',
    databaseURL: 'https://mdpgold-eca4c-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-eca4c.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi0e6NUnuN6Bi55KNCMMj8WpbPWC_LNSY',
    appId: '1:570068908413:web:59a032e11d54b96ff0f414',
    messagingSenderId: '570068908413',
    projectId: 'mdpgold-eca4c',
    authDomain: 'mdpgold-eca4c.firebaseapp.com',
    databaseURL: 'https://mdpgold-eca4c-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-eca4c.firebasestorage.app',
    measurementId: 'G-6TTC4RXF86',
  );

}